# These are supported funding model platforms
# See: https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/displaying-a-sponsor-button-in-your-repository

github: [nuvc-ai]
# ko_fi: minifi
# buy_me_a_coffee: minifi
# custom: ["https://donate.minifi.app"]

# MiniFi v1.0
